### PR TITLE
Added SIDEKIQ_SNITCH_DELAY_MINUTES env variable

### PR DESCRIPTION
**Pull request by imme5150**
Allow people to configure the delay

### CODE REVIEW

**Comment by tilsammans** [comment]
I would rather not have this being so free, but follow the intervals that DMS offers:

* 15 minute
* 30 minute
* hour
* day
* week
* month

For this I want to implement a configuration object. It should give you all the flexibility you need but not too much, as the interval must be close to the interval you choose in DMS.

**Comment by imme5150** [comment]
I think it's a better user experience to allow people to set the number directly.  There are a number of similar services out there.  We are actually using healthchecks.io and they let you set any frequency you want.

**Comment by tilsammans** [comment]
that's dope, didn't know about them!

**Comment by tilsammans** [comment]
I‘ve stopped maintaining this gem, since I think OkComputer is a superior solution to monitoring your Sidekiq queue. You would add one for each queue, and then check the /okcomputer endpoint for everything.

**Pull request closed without merging**
